name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: one
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: 56369861fe6300838cf3f8f308b40c54
          user: ZianTT
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_introduction: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          repositories_affiliations: collaborator
          commits_authoring: ZianTT, 2508164094@qq.com, ziantt@duck.com, 53261506+ZianTT@users.noreply.github.com, ziantt@lightxi.com
          plugin_habits: yes
          plugin_habits_facts: yes
      - name: two
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: af3eb4b2a2319ecf2821d475966bb50b
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
